routes/web.php
            Route::post('config_cost_store_freight', ['as' => 'config_cost_store_freight', 'uses' => 'AdController@config_cost_store_freight']);
            Route::get('config_cost/{id}', ['as' => 'config_cost_edit', 'uses' => 'AdController@config_cost_edit']);
            Route::patch('config_cost/{id}', ['as' => 'config_cost_update', 'uses' => 'AdController@config_cost_update']);
            Route::delete('config_cost_destroy/{id}', ['as' => 'config_cost_destroy', 'uses' => 'AdController@config_cost_destroy']);
            Route::get('simulation', ['as' => 'simulation', 'uses' => 'AdController@simulation']);
            Route::post('import_profit', ['as' => 'import_profit', 'uses' => 'AdController@import_profit']);
            Route::post('import_item', ['as' => 'import_item', 'uses' => 'AdController@import_item']);
            Route::get('ajax_get_ad_sales', ['as' => 'ajax_get_ad_sales', 'uses' => 'AdController@ajax_get_ad_sales']);
        });
        //銷貨報表
        Route::group(['prefix' => 'sales', 'as' => 'sales.'], function () {
            Route::get('report', ['as' => 'report', 'uses' => 'SalesController@report']);
            Route::get('performance', ['as' => 'performance', 'uses' => 'SalesController@performance']);
            Route::get('cust_item', ['as' => 'cust_item', 'uses' => 'SalesController@cust_item']);
            Route::get('item_kind_sales', ['as' => 'item_kind_sales', 'uses' => 'SalesController@item_kind_sales']);
            Route::get('item_kind3_sales', ['as' => 'item_kind3_sales', 'uses' => 'SalesController@item_kind3_sales']);
            Route::get('item_sales', ['as' => 'item_sales', 'uses' => 'SalesController@item_sales']);
            Route::get('floor', ['as' => 'floor', 'uses' => 'SalesController@floor']);
            Route::get('shopee_trans', ['as' => 'shopee_trans', 'uses' => 'SalesController@shopee_trans']);
            Route::get('shopee_discount', ['as' => 'shopee_discount', 'uses' => 'SalesController@shopee_discount']);
            Route::post('import', ['as' => 'import', 'uses' => 'SalesController@import']);
        });
        //保固網站管理
        Route::group(['prefix' => 'warranty_web', 'as' => 'warranty_web.'], function () {
            Route::get('search', ['as' => 'search', 'uses' => 'WarrantyWebController@search']);
            Route::get('video_config', ['as' => 'video_config', 'uses' => 'WarrantyWebController@video_config']);
            Route::get('video_config/create', ['as' => 'video_config_create', 'uses' => 'WarrantyWebController@video_config_create']);
            Route::post('video_config', ['as' => 'video_config_store', 'uses' => 'WarrantyWebController@video_config_store']);
            Route::get('video_config/{id}', ['as' => 'video_config_edit', 'uses' => 'WarrantyWebController@video_config_edit']);
            Route::patch('video_config/{id}', ['as' => 'video_config_update', 'uses' => 'WarrantyWebController@video_config_update']);
            Route::delete('video_config/{id}', ['as' => 'video_config_destroy', 'uses' => 'WarrantyWebController@video_config_destroy']);
            Route::get('item_config', ['as' => 'item_config', 'uses' => 'WarrantyWebController@item_config']);
            Route::post('item_import', ['as' => 'item_import', 'uses' => 'WarrantyWebController@item_import']);
        });

        //幫助中心
        Route::group(['prefix' => 'help', 'as' => 'help.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'HelpController@index']);
            Route::get('search', ['as' => 'search', 'uses' => 'HelpController@search']);
            Route::get('create', ['as' => 'create', 'uses' => 'HelpController@create']);
            Route::get('edit_index', ['as' => 'edit_index', 'uses' => 'HelpController@edit_index']);
            Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'HelpController@edit']);
            Route::patch('edit/{id}', ['as' => 'update', 'uses' => 'HelpController@update']);
            Route::patch('restore/{id}', ['as' => 'restore', 'uses' => 'HelpController@restore']);
            Route::post('store', ['as' => 'store', 'uses' => 'HelpController@store']);
            Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'HelpController@destroy']);
            Route::delete('force_destroy/{id}', ['as' => 'force_destroy', 'uses' => 'HelpController@force_destroy']);
            Route::get('ajax_get_ans', ['as' => 'ajax_get_ans', 'uses' => 'HelpController@ajax_get_ans']);
        });

        //商品行銷設定
        Route::group(['prefix' => 'item_marketing', 'as' => 'item_marketing.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'ItemMarketingController@index']);
            Route::get('create', ['as' => 'create', 'uses' => 'ItemMarketingController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'ItemMarketingController@store']);
            Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'ItemMarketingController@edit']);
            Route::patch('edit/{id}', ['as' => 'update', 'uses' => 'ItemMarketingController@update']);
            Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'ItemMarketingController@destroy']);
        });

        //物流地區註記
        Route::group(['prefix' => 'logistics_addr_mark', 'as' => 'logistics_addr_mark.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'LogisticsAddrMarkController@index']);
            Route::get('create', ['as' => 'create', 'uses' => 'LogisticsAddrMarkController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'LogisticsAddrMarkController@store']);
            Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'LogisticsAddrMarkController@destroy']);
        });

        //計算機
        Route::group(['prefix' => 'tool', 'as' => 'tool.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'ToolController@index']);
            Route::get('floor_sales', ['as' => 'floor_sales', 'uses' => 'ToolController@floor_sales']);
            Route::get('personal_transport_count', ['as' => 'personal_transport_count', 'uses' => 'ToolController@personal_transport_count']);
        });
        //包裝作業
        Route::group(['prefix' => 'package', 'as' => 'package.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'PackageController@index']);
            Route::get('check_start', ['as' => 'check_start', 'uses' => 'PackageController@check_start']);
            Route::post('check_store/{sale_no}', ['as' => 'check_store', 'uses' => 'PackageController@check_store']);
            Route::get('start', ['as' => 'start', 'uses' => 'PackageController@start']);
            Route::get('end', ['as' => 'end', 'uses' => 'PackageController@end']);
            Route::get('list', ['as' => 'list', 'uses' => 'PackageController@list']);
            Route::get('order_packager', ['as' => 'order_packager', 'uses' => 'PackageController@order_packager']);
        });
        //產品紀錄
        Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
            Route::group(['prefix' => 'sample', 'as' => 'sample.'], function () {
                Route::post('confirm/{id}', ['as' => 'confirm', 'uses' => 'Product\SampleController@confirm']);
                Route::get('index', ['as' => 'index', 'uses' => 'Product\SampleController@index']);
                Route::get('create', ['as' => 'create', 'uses' => 'Product\SampleController@create']);
                Route::post('store', ['as' => 'store', 'uses' => 'Product\SampleController@store']);
                Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'Product\SampleController@edit']);
                Route::patch('update/{id}', ['as' => 'update', 'uses' => 'Product\SampleController@update']);
                Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'Product\SampleController@destroy']);
                Route::get('detail/{id}', ['as' => 'detail', 'uses' => 'Product\SampleController@detail']);
                Route::get('detail_create/{id}', ['as' => 'detail_create', 'uses' => 'Product\SampleController@detail_create']);
                Route::post('detail_store/{id}', ['as' => 'detail_store', 'uses' => 'Product\SampleController@detail_store']);
                Route::get('detail_edit/{id}', ['as' => 'detail_edit', 'uses' => 'Product\SampleController@detail_edit']);
                Route::patch('detail_update/{id}', ['as' => 'detail_update', 'uses' => 'Product\SampleController@detail_update']);
                Route::delete('detail_destroy/{id}', ['as' => 'detail_destroy', 'uses' => 'Product\SampleController@detail_destroy']);
            });
            Route::group(['prefix' => 'erp', 'as' => 'erp.'], function () {
                Route::post('confirm/{id}', ['as' => 'confirm', 'uses' => 'Product\ErpController@confirm']);
                Route::get('index', ['as' => 'index', 'uses' => 'Product\ErpController@index']);
                Route::get('detail/{id}', ['as' => 'detail', 'uses' => 'Product\ErpController@detail']);
                Route::get('detail_edit/{id}', ['as' => 'detail_edit', 'uses' => 'Product\ErpController@detail_edit']);
                Route::patch('detail_update/{id}', ['as' => 'detail_update', 'uses' => 'Product\ErpController@detail_update']);
                Route::post('export', ['as' => 'export', 'uses' => 'Product\ErpController@export']);
                Route::post('print', ['as' => 'print', 'uses' => 'Product\ErpController@print']);
            });
            //商品提案
            Route::group(['prefix' => 'proposal', 'as' => 'proposal.'], function () {
                Route::get('index', ['as' => 'index', 'uses' => 'Product\ProposalController@index']);
                Route::get('create', ['as' => 'create', 'uses' => 'Product\ProposalController@create']);
                Route::post('store', ['as' => 'store', 'uses' => 'Product\ProposalController@store']);

app/Models/yherp/HelpActions.php
<?php

namespace App\Models\yherp;

use App\Models\yherp\HelpQuestions;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class HelpActions extends Model
{
    use SoftDeletes;

    protected $connection = 'mysql';
    protected $table = 'help_actions';

    protected $fillable = [
        'name',
    ];

    public function Questions()
    {
        return $this->hasMany(HelpQuestions::class, 'action_id', 'id');
    }
}

resources/views/help/index.blade.php
@extends('layouts.base')
@section('title')
    幫助中心
@stop
@section('css')
    <style type="text/css">
    </style>
@endsection
@section('content')
    <div class="container-fluid">
        <div class="form-row mb-3">
            <div class="col-8">
                <form action="{{ route('help.search') }}" method="GET">
                    <div class="form-row">
                        <div class="form-group col-7">
                            <label>銷售平台</label>
                            <div class="form-check-list-horizontal">
                                @foreach ($shops as $shop)
                                    <div class="form-check">
                                        <input class="form-check-input" id="input_shop_{{ $shop->id }}" name="shop"
                                            type="radio" value="{{ $shop->id }}"
                                            {{ (empty(old('shop')) && $loop->first) || old('shop') == $shop->id ? 'checked' : '' }}>
                                        <label class="form-check-label" for="input_shop_{{ $shop->id }}">
                                            {{ $shop->name }}
                                        </label>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <div class="form-group col-3">
                            <label>行為</label>
                            <div class="form-check-list-horizontal">
                                @foreach ($actions as $action)
                                    <div class="form-check">
                                        <input class="form-check-input" id="input_action_{{ $action->id }}" name="action"
                                            type="radio" value="{{ $action->id }}"
                                            {{ (empty(old('action')) && $loop->first) || old('action') == $action->id ? 'checked' : '' }}>
                                        <label class="form-check-label" for="input_action_{{ $action->id }}">
                                            {{ $action->name }}
                                        </label>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-4">
                            <label>問題歸類</label>
                            <div class="form-check-list-horizontal">
                                <div class="form-check">
                                    <input class="form-check-input" id="input_type_0" name="type" type="radio"
                                        value="" checked>
                                    <label class="form-check-label" for="input_type_0">通用類</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" id="input_type_1" name="type" type="radio"
                                        value="1">
                                    <label class="form-check-label" for="input_type_1">指定大中小類</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" id="input_type_2" name="type" type="radio"
                                        value="2">
                                    <label class="form-check-label" for="input_type_2">指定料號</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-1 kind" style="display: none;">
                            <label for="input_kind">大類</label>
                            <input type="text" name="kind" id="input_kind" list="kind_list" class="form-control"
                                autocomplete="off" value="{{ old('kind') }}">
                        </div>
                        <div class="form-group col-1 kind" style="display: none;">
                            <label for="input_kind2">中類</label>
                            <input type="text" name="kind2" id="input_kind2" list="kind2_list" class="form-control"
                                autocomplete="off" value="{{ old('kind2') }}">
                        </div>
                        <div class="form-group col-1 kind" style="display: none;">
                            <label for="input_kind3">小類</label>
                            <input type="text" name="kind3" id="input_kind3" list="kind3_list" class="form-control"
                                autocomplete="off" value="{{ old('kind3') }}">
                        </div>
                        <div class="form-group col-2 item" style="display: none;">
                            <label for="input_td">料號</label>
                            <input type="text" name="id" id="input_td" list="item_list" class="form-control"
                                autocomplete="off" value="{{ old('id') }}">
                        </div>
                    </div>
                    <button class="btn btn-primary btn-sm" type="submit">查詢</button>
                </form>
            </div>
            <div class="col"></div>
            @can('help_modify')
                <div class="col-auto">
                    <a class="btn btn-warning btn-sm" href="{{ route('help.edit_index') }}">
                        <i class="bi bi-pencil-fill"></i>編輯題庫
                    </a>
                </div>
            @endcan
        </div>
        <datalist id="kind_list">
            @if (!empty($types))
                @foreach ($types[1] as $value => $text)
                    <option value="{{ $value }}">{{ $text }}</option>
                @endforeach
            @endif
        </datalist>
        <datalist id="kind2_list">
            @if (!empty($types))
                @foreach ($types[2] as $value => $text)
                    <option value="{{ $value }}">{{ $text }}</option>
                @endforeach
            @endif
        </datalist>
        <datalist id="kind3_list">
            @if (!empty($types))
                @foreach ($types[3] as $value => $text)
                    <option value="{{ $value }}">{{ $text }}</option>
                @endforeach
            @endif
        </datalist>
        <datalist id="item_list">
            @if (!empty($items))
                @foreach ($items as $item)
                    <option value="{{ $item->item_no }}">{{ $item->item_name }}</option>
                @endforeach
            @endif
        </datalist>
    @stop
    @section('script')
        <script type="text/javascript">
            //通用類與指定大中小類切換
            $('[name="type"]').on('change', function() {
                $('.kind,.item').hide();
                $('.kind>input,.item>input').val('');
                if ($('#input_type_1').prop('checked')) { //大中小類
                    $('.kind').show();
                } else if ($('#input_type_2').prop('checked')) { //料號
                    $('.item').show();
                }
            });
        </script>
    @stop

resources/views/help/search.blade.php
@extends('layouts.master')
@section('master_title')
    幫助中心查詢結果
@stop
@section('master_css')
    <style type="text/css">
        .types>span {
            padding-left: 2rem;
        }

        .badge {
            font-size: 1.5rem;
        }

        .questions .card-body {
            max-height: 70vh;
            overflow: auto;
        }

        .question:hover {
            background-color: #999;
            color: white;
        }

        .questions .list-group-item {
            border: 0;
            cursor: pointer;
        }

        .answer .imgs img {
            max-width: 100px;
            max-height: 100px;
            margin: 0 0.25rem;
            cursor: pointer;
        }

        #modal_image img {
            max-width: 100%;
            margin: auto;
        }

        #loading {
            width: 200px;
            height: 200px;
            border-width: 20px;
            position: absolute;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            margin: auto;
        }

        div#lockscreen {
            width: 0;
            height: 0;
            position: fixed;
            top: 0;
            left: 0;
            display: none;
            background-color: rgba(0, 0, 0, 0.2);
        }

        /*open on another modal*/
        .modal:nth-of-type(even) {
            z-index: 1052 !important;
        }

        .modal-backdrop.show:nth-of-type(even) {
            z-index: 1051 !important;
        }
    </style>
@endsection
@section('master_body')
    {{-- Modal 問題解答 --}}
    <div id="modal_answer" class="modal">
        <div class="modal-dialog modal-dialog-centered" style="max-width: 95%;">
            <div class="modal-content answer">
                <div class="modal-header">
                    <h2 class="modal-title"></h2>
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <ul class="list-group">
                        <li class="list-group-item p-0 remark">
                            <h3 class="p-3">內部備註</h3>
                            <div class="p-3"></div>
                        </li>
                        <li class="list-group-item p-0 content">
                            <h3 class="p-3">答案</h3>
                            <div class="p-3"></div>
                        </li>
                        <li class="list-group-item p-0 imgs">
                            <h3 class="p-3">附圖</h3>
                            <div class="p-3"></div>
                        </li>
                    </ul>
                </div>
                <div class="modal-footer">
                    <div class="form-row align-items-center w-100">
                        <div class="col-auto updated_at text-danger">最後更新時間：<span></span></div>
                        <div class="col"></div>
                        <div class="col-auto">
                            <button id="btn_copy" class="btn btn-success" type="button">
                                <i class="bi bi-clipboard"></i>複製答案
                            </button>
                        </div>
                        <div class="col-auto">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">關閉</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{-- Modal 詳細圖片 --}}
    <div id="modal_image" class="modal" data-backdrop="static">
        <div class="modal-dialog modal-dialog-centered" style="max-width: 95%;">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">詳細圖片</h2>
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div style="overflow-y: auto; max-height: 70vh;">
                        <img id="img_detail" class="d-block">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">關閉</button>
                </div>
            </div>
        </div>
    </div>
    {{-- 讀取鎖定畫面，需放在modal後面 --}}
    <div id="lockscreen">
        <div id="loading" class="spinner-border text-secondary"></div>
    </div>
    <div class="container-fluid">
        <div class="form-row mt-2">
            <div class="col-12">
                <h2>查詢條件</h2>
            </div>
            <div class="col-auto">
                <span class="badge badge-secondary">{{ $input_data['shop'] }}</span>
            </div>
            <div class="col-auto">
                <span class="badge badge-success">{{ $input_data['action'] }}</span>
            </div>
            <div class="col-auto">
                <span class="badge text-white types"
                    style="background-color: var(--orange)">{{ $input_data['type_name'] }}</span>
                @switch($input_data['type'])
                    @case(1)
                        @if (!empty($input_data['kind']))
                            <span class="badge badge-dark">大類【{{ $input_data['kind'] }}】{{ $input_data['kind_name'] }}</span>
                        @endif
                        @if (!empty($input_data['kind2']))
                            <span class="badge badge-dark">中類【{{ $input_data['kind2'] }}】{{ $input_data['kind2_name'] }}</span>
                        @endif
                        @if (!empty($input_data['kind3']))
                            <span class="badge badge-dark">小類【{{ $input_data['kind3'] }}】{{ $input_data['kind3_name'] }}</span>
                        @endif
                    @break

                    @case(2)
                        @if (!empty($input_data['item_no']))
                            <span class="badge badge-dark">【{{ $input_data['item_no'] }}】{{ $input_data['item_name'] }}</span>
                        @endif
                    @break

                @endswitch

            </div>
        </div>
        <hr>
        <div class="form-row questions">
            <div class="col-12">
                <h2>問題清單</h2>
            </div>
            <div class="col-4">
                @if (!empty($data['universal']) && count($data['universal']) > 0)
                    <div class="card">
                        <h1 class="card-header text-white bg-info font-weight-bold">通用類</h1>
                        <div class="card-body p-0">
                            <ul class="list-group">
                                @foreach ($data['universal']->sortBy('content') as $question)
                                    <li class="question list-group-item" data-id="{{ $question->id }}">
                                        <span>{{ $question->content }}</span>
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif
            </div>
            <div class="col-4">
                @if (!empty($data['kind']) && count($data['kind']) > 0)
                    <div class="card">
                        <h1 class="card-header text-white bg-success font-weight-bold">大中小類</h1>
                        <div class="card-body p-0">
                            <ul class="list-group">
                                @foreach ($data['kind']->sortBy('content') as $question)
                                    <li class="question list-group-item" data-id="{{ $question->id }}">
                                        <span>{{ $question->content }}</span>
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif
            </div>
            <div class="col-4">
                @if (!empty($data['item']) && count($data['item']) > 0)
                    <div class="card">
                        <h1 class="card-header text-white bg-warning font-weight-bold">料號</h1>
                        <div class="card-body p-0">
                            <ul class="list-group">
                                @foreach ($data['item']->sortBy('content') as $question)
                                    <li class="question list-group-item" data-id="{{ $question->id }}">
                                        <span>{{ $question->content }}</span>
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
@stop
@section('master_js')
    <script type="text/javascript">
        var url = "{{ route('help.ajax_get_ans') }}";
        $('.question').click(function() {
            lockScreen();
            //show loading
            $('.answer .content>div').html('');
            //get answer
            var id = $(this).data().id;
            var data = '';
            $.ajax({
                url: url,
                type: "get",
                dataType: 'json',
                data: {
                    id: id,
                },
                contentType: "application/json",
                success: function(d) {
                    if (!$.isEmptyObject(d)) {
                        data = d;
                    }
                },
                error: function(xhr, ajaxOptions, thrownError) {
                    alert(JSON.parse(xhr.responseText).msg);
                },
                complete: function() {
                    SetAnswer(data);
                    $('#modal_answer').modal('show');
                    unlockScreen();
                }
            });
        });
        //設定答案內容
        function SetAnswer(data) {
            var question = data.content;
            var remark = data.remark; //內部備註
            var content = data.answer; //答案
            var imgs = data.imgs; //圖片
            var updated_at = data.updated_at; //更新時間
            $('.answer .modal-title').text(question);
            //答案
            $('.answer .content>div').html(content);
            //內部備註
            if (IsNullOrEmpty(remark)) {
                $('.answer .remark').hide();
                $('.answer .remark>div').html('');
            } else {
                $('.answer .remark').show();
                $('.answer .remark>div').html(remark);
            }
            //圖片
            $('.imgs>div').html('');
            if (imgs.length > 0) {
                $(imgs).each(function(index, element) {
                    var path = element.path;
                    var img = document.createElement('img');
                    img.src = '{{ asset('storage') }}' + '/' + path;
                    img.onclick = ZoomImg;
                    img.onload = function() {
                        URL.revokeObjectURL(img.src) // free memory
                    }
                    $('.imgs>div').append(img);
                });
                $('.imgs').show();
            } else {
                $('.imgs').hide();
            }
            //更新時間
            $('.answer .updated_at>span').text(updated_at);
        }
        //複製剪貼簿
        $("#btn_copy").click(function() {
            var value = $(".content>div").text();
            const el = document.createElement('textarea');
            el.value = value;
            document.body.appendChild(el);
            el.select();
            document.execCommand('copy');
            document.body.removeChild(el);
            alert('已複製到剪貼簿');
        });
        //鎖定螢幕點選
        function lockScreen() {
            $("#lockscreen").css("width", "100%");
            $("#lockscreen").css("height", "100%");
            $("#lockscreen").css("z-index", "10000");
            $("#lockscreen").css("display", "block");
        }
        //解鎖螢幕點選
        function unlockScreen() {
            $("#lockscreen").css("width", "0");
            $("#lockscreen").css("height", "0");
            $("#lockscreen").css("z-index", "0");
            $("#lockscreen").css("display", "none");
        }
        //詳細圖片
        function ZoomImg() {
            var src = $(this).prop('src');
            $('#img_detail').prop('src', src);
            $('#modal_image').modal('show');
        }
    </script>
@stop