routes/web.php
            Route::post('import', ['as' => 'import', 'uses' => 'SalesController@import']);
        });
        //保固網站管理
        Route::group(['prefix' => 'warranty_web', 'as' => 'warranty_web.'], function () {
            Route::get('search', ['as' => 'search', 'uses' => 'WarrantyWebController@search']);
            Route::get('video_config', ['as' => 'video_config', 'uses' => 'WarrantyWebController@video_config']);
            Route::get('video_config/create', ['as' => 'video_config_create', 'uses' => 'WarrantyWebController@video_config_create']);
            Route::post('video_config', ['as' => 'video_config_store', 'uses' => 'WarrantyWebController@video_config_store']);
            Route::get('video_config/{id}', ['as' => 'video_config_edit', 'uses' => 'WarrantyWebController@video_config_edit']);
            Route::patch('video_config/{id}', ['as' => 'video_config_update', 'uses' => 'WarrantyWebController@video_config_update']);
            Route::delete('video_config/{id}', ['as' => 'video_config_destroy', 'uses' => 'WarrantyWebController@video_config_destroy']);
            Route::get('item_config', ['as' => 'item_config', 'uses' => 'WarrantyWebController@item_config']);
            Route::post('item_import', ['as' => 'item_import', 'uses' => 'WarrantyWebController@item_import']);
        });

        //幫助中心
        Route::group(['prefix' => 'help', 'as' => 'help.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'HelpController@index']);
            Route::get('search', ['as' => 'search', 'uses' => 'HelpController@search']);
            Route::get('create', ['as' => 'create', 'uses' => 'HelpController@create']);
            Route::get('edit_index', ['as' => 'edit_index', 'uses' => 'HelpController@edit_index']);
            Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'HelpController@edit']);
            Route::patch('edit/{id}', ['as' => 'update', 'uses' => 'HelpController@update']);
            Route::patch('restore/{id}', ['as' => 'restore', 'uses' => 'HelpController@restore']);
            Route::post('store', ['as' => 'store', 'uses' => 'HelpController@store']);
            Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'HelpController@destroy']);
            Route::delete('force_destroy/{id}', ['as' => 'force_destroy', 'uses' => 'HelpController@force_destroy']);
            Route::get('ajax_get_ans', ['as' => 'ajax_get_ans', 'uses' => 'HelpController@ajax_get_ans']);
        });

        //商品行銷設定
        Route::group(['prefix' => 'item_marketing', 'as' => 'item_marketing.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'ItemMarketingController@index']);
            Route::get('create', ['as' => 'create', 'uses' => 'ItemMarketingController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'ItemMarketingController@store']);
            Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'ItemMarketingController@edit']);
            Route::patch('edit/{id}', ['as' => 'update', 'uses' => 'ItemMarketingController@update']);
            Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'ItemMarketingController@destroy']);
        });

        //物流地區註記
        Route::group(['prefix' => 'logistics_addr_mark', 'as' => 'logistics_addr_mark.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'LogisticsAddrMarkController@index']);
            Route::get('create', ['as' => 'create', 'uses' => 'LogisticsAddrMarkController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'LogisticsAddrMarkController@store']);
            Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'LogisticsAddrMarkController@destroy']);
        });

        //計算機
        Route::group(['prefix' => 'tool', 'as' => 'tool.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'ToolController@index']);
            Route::get('floor_sales', ['as' => 'floor_sales', 'uses' => 'ToolController@floor_sales']);
            Route::get('personal_transport_count', ['as' => 'personal_transport_count', 'uses' => 'ToolController@personal_transport_count']);
        });
        //包裝作業
        Route::group(['prefix' => 'package', 'as' => 'package.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'PackageController@index']);
            Route::get('check_start', ['as' => 'check_start', 'uses' => 'PackageController@check_start']);
            Route::post('check_store/{sale_no}', ['as' => 'check_store', 'uses' => 'PackageController@check_store']);
            Route::get('start', ['as' => 'start', 'uses' => 'PackageController@start']);
            Route::get('end', ['as' => 'end', 'uses' => 'PackageController@end']);
            Route::get('list', ['as' => 'list', 'uses' => 'PackageController@list']);
            Route::get('order_packager', ['as' => 'order_packager', 'uses' => 'PackageController@order_packager']);
        });
        //產品紀錄
        Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
            Route::group(['prefix' => 'sample', 'as' => 'sample.'], function () {
                Route::post('confirm/{id}', ['as' => 'confirm', 'uses' => 'Product\SampleController@confirm']);
                Route::get('index', ['as' => 'index', 'uses' => 'Product\SampleController@index']);
                Route::get('create', ['as' => 'create', 'uses' => 'Product\SampleController@create']);
                Route::post('store', ['as' => 'store', 'uses' => 'Product\SampleController@store']);
                Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'Product\SampleController@edit']);
                Route::patch('update/{id}', ['as' => 'update', 'uses' => 'Product\SampleController@update']);
                Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'Product\SampleController@destroy']);
                Route::get('detail/{id}', ['as' => 'detail', 'uses' => 'Product\SampleController@detail']);
                Route::get('detail_create/{id}', ['as' => 'detail_create', 'uses' => 'Product\SampleController@detail_create']);
                Route::post('detail_store/{id}', ['as' => 'detail_store', 'uses' => 'Product\SampleController@detail_store']);
                Route::get('detail_edit/{id}', ['as' => 'detail_edit', 'uses' => 'Product\SampleController@detail_edit']);
                Route::patch('detail_update/{id}', ['as' => 'detail_update', 'uses' => 'Product\SampleController@detail_update']);
                Route::delete('detail_destroy/{id}', ['as' => 'detail_destroy', 'uses' => 'Product\SampleController@detail_destroy']);
            });
            Route::group(['prefix' => 'erp', 'as' => 'erp.'], function () {
                Route::post('confirm/{id}', ['as' => 'confirm', 'uses' => 'Product\ErpController@confirm']);
                Route::get('index', ['as' => 'index', 'uses' => 'Product\ErpController@index']);
                Route::get('detail/{id}', ['as' => 'detail', 'uses' => 'Product\ErpController@detail']);
                Route::get('detail_edit/{id}', ['as' => 'detail_edit', 'uses' => 'Product\ErpController@detail_edit']);
                Route::patch('detail_update/{id}', ['as' => 'detail_update', 'uses' => 'Product\ErpController@detail_update']);
                Route::post('export', ['as' => 'export', 'uses' => 'Product\ErpController@export']);
                Route::post('print', ['as' => 'print', 'uses' => 'Product\ErpController@print']);
            });
            //商品提案
            Route::group(['prefix' => 'proposal', 'as' => 'proposal.'], function () {
                Route::get('index', ['as' => 'index', 'uses' => 'Product\ProposalController@index']);
                Route::get('create', ['as' => 'create', 'uses' => 'Product\ProposalController@create']);
                Route::post('store', ['as' => 'store', 'uses' => 'Product\ProposalController@store']);
                Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'Product\ProposalController@edit']);
                Route::patch('update/{id}', ['as' => 'update', 'uses' => 'Product\ProposalController@update']);
                Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'Product\ProposalController@destroy']);
                Route::post('return/{id}', ['as' => 'return', 'uses' => 'Product\ProposalController@return']);
                Route::get('ajax_check_repeat', ['as' => 'ajax_check_repeat', 'uses' => 'Product\ProposalController@ajax_check_repeat']);
            });
        });
        //調轉確認作業
        Route::group(['prefix' => 'order_confirm', 'as' => 'order_confirm.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'OrderConfirmController@index']);
            Route::post('store', ['as' => 'store', 'uses' => 'OrderConfirmController@store']);
        });
        //盤點作業
        Route::group(['prefix' => 'inventory', 'as' => 'inventory.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'InventoryController@index']);
            Route::get('create', ['as' => 'create', 'uses' => 'InventoryController@create']);
            Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'InventoryController@edit']);
            Route::patch('update/{id}', ['as' => 'update', 'uses' => 'InventoryController@update']);
            Route::post('inventory_done/{id}', ['as' => 'inventory_done', 'uses' => 'InventoryController@inventory_done']);
            Route::post('complete/{id}', ['as' => 'complete', 'uses' => 'InventoryController@complete']);
            Route::post('store', ['as' => 'store', 'uses' => 'InventoryController@store']);
            Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'InventoryController@destroy']);
            Route::post('export/{id}', ['as' => 'export', 'uses' => 'InventoryController@export']);
        });
        //收料作業
        Route::group(['prefix' => 'receipt', 'as' => 'receipt.'], function () {

app/Models/yherp/LogisticsAddrMark.php
<?php

namespace App\Models\yherp;

use App\Models\yherp\County;
use App\Models\yherp\CountyArea;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class LogisticsAddrMark extends Model
{
    use SoftDeletes;

    protected $connection = 'mysql';
    protected $table = 'logistics_addr_mark';

    protected $fillable = [
        'kind', 'county_id', 'area_id'
    ];

    public function County()
    {
        return $this->belongsTo(County::class, 'county_id', 'id');
    }

    public function Area()
    {
        return $this->belongsTo(CountyArea::class, 'area_id', 'id');
    }
}

app/Http/Controllers/LogisticsAddrMarkController.php
<?php

namespace App\Http\Controllers;

use App\Models\yherp\CountyArea;
use App\Models\yherp\County;
use Illuminate\Http\Request;
use App\Models\yherp\LogisticsAddrMark;
use App\Http\Controllers\Controller;

class LogisticsAddrMarkController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:logistics_addr_mark');
    }

    //首頁
    function index()
    {
        $data = LogisticsAddrMark::with('county', 'area')->get()->sortBy('kind')->sortBy('county_id')->sortBy('area_id');
        return view('logistics_addr_mark.index', compact('data'));
    }

    public function create()
    {
        $countys = County::all();
        $areas = CountyArea::all();
        return view('logistics_addr_mark.create', compact('countys', 'areas'));
    }

    public function store(Request $request)
    {
        //驗證
        $this->validate($request, [
            'kind' => 'required',
            'county' => ['required', 'exists:mysql.county,id'],
            'area' => ['required', 'exists:mysql.county_area,id'],
        ]);
        LogisticsAddrMark::create([
            'kind' => $request->get('kind'),
            'county_id' => $request->get('county'),
            'area_id' => $request->get('area'),
        ]);

        return redirect()->route('logistics_addr_mark.index')
            ->with('status', '新增成功');
    }

    //刪除
    function destroy($id)
    {
        $m = LogisticsAddrMark::find($id);
        $m->delete();
        return redirect()->route('logistics_addr_mark.index')
            ->with('status', '刪除成功');
    }
}

resources/views/logistics_addr_mark/create.blade.php
@extends('layouts.base')
@section('title')
    物流地區註記-新增
@stop
@section('css')
    <style type="text/css">

    </style>
@endsection
@section('content')
    <div class="container-fluid">
        @if ($errors->any())
            <div class="form-row mb-2">
                <div class="col-auto">
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        @endif
        <div class="form-row">
            <div class="col-auto">
                <a class="btn btn-secondary" href="{{ route('logistics_addr_mark.index') }}">回上頁</a>
            </div>
        </div>
        <hr>
        <form method="POST" action="{{ route('logistics_addr_mark.store') }}" class="mb-2">
            @csrf
            <div class="form-row mt-2">
                <div class="col-2">
                    <div class="form-group">
                        <label class="text-danger" for="select_kind">*類別</label>
                        <select class="custom-select" id="select_kind" name="kind" required>
                            <option value="" selected>請選擇...</option>
                            <option value="1">音速配送地區</option>
                            <option value="2">新竹偏遠地區</option>
                        </select>
                    </div>
                </div>
                <div class="col-2">
                    <div class="form-group">
                        <label class="text-danger" for="input_county">*縣市</label>
                        <div class="input-group">
                            <input class="form-control" id="input_county" name="county" type="text" list="county_list"
                                required>
                            <div class="input-group-append">
                                <span class="input-group-text" id="span_county">請選擇縣市</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    <div class="form-group">
                        <label class="text-danger" for="input_area">*鄉鎮市區</label>
                        <div class="input-group">
                            <input class="form-control" id="input_area" name="area" type="text" list="area_list"
                                required>
                            <div class="input-group-append">
                                <span class="input-group-text" id="span_area">請選擇鄉鎮市區</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <button id="btn_confirm" class="btn btn-primary" type="submit">確認</button>
        </form>
    </div>
    <datalist id="county_list">
        @if (!empty($countys))
            @foreach ($countys as $county)
                <option value="{{ $county->id }}">{{ $county->name }}</option>
            @endforeach
        @endif
    </datalist>
    <datalist id="area_list">
        @if (!empty($areas))
            @foreach ($areas as $area)
                <option value="{{ $area->id }}" data-county="{{ $area->county_id }}" disabled="disabled">
                    {{ $area->name }}</option>
            @endforeach
        @endif
    </datalist>
@stop
@section('script')
    <script type="text/javascript">
        $('#input_county,#input_area').change(function() {
            var kind = $(this).prop('name');
            var val = $(this).val();
            var text = $('#' + kind + '_list>option[value="' + val + '"]').text();
            $(this).find('+div>span').text(text);
            //根據 縣市 設定 鄉鎮市區
            if (kind == 'county') {
                $('#input_area').val('');
                $('#input_area+div>span').text('請選擇鄉鎮市區');
                $('#area_list>option[data-county="' + val + '"]').prop('disabled', '');
                $('#area_list>option[data-county!="' + val + '"]').prop('disabled', 'disabled');
            }
        });
    </script>
@stop

resources/views/logistics_addr_mark/index.blade.php
@extends('layouts.base')
@section('title')
    物流地區標記
@stop
@section('css')
    <style type="text/css">
    </style>
@endsection
@section('content')
    <div class="container">
        <div class="form-row">
            <div class="col"></div>
            <div class="col-auto">
                <a class="btn btn-info" href="{{ route('logistics_addr_mark.create') }}">
                    <i class="bi bi-plus-lg"></i>新增
                </a>
            </div>
        </div>
        <hr>
        <div class="form-row">
            <div class="col">
                @if (!empty($data) && count($data) > 0)
                    <div class="FrozenTable" style="max-height: 85vh;">
                        <table class="table table-bordered table-hover sortable table-filter">
                            <thead>
                                <tr>
                                    <th style="width: 8%;">流水號</th>
                                    <th class="filter-col">類別</th>
                                    <th class="filter-col" style="width: 20%;">縣市</th>
                                    <th style="width: 20%;">鄉鎮市區</th>
                                    <th style="width: 10%;">操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($data as $item)
                                    <tr>
                                        <td>{{ $item->id }}</td>
                                        <td>
                                            @switch($item->kind)
                                                @case(1)
                                                    音速配送地區
                                                @break

                                                @case(2)
                                                    新竹偏遠地區
                                                @break
                                            @endswitch
                                        </td>
                                        <td>{{ $item->county->name }}</td>
                                        <td>{{ $item->area->name }}</td>
                                        <td>
                                            <div class="mx-1">
                                                <form method="POST"
                                                    action="{{ route('logistics_addr_mark.destroy', $item->id) }}"
                                                    onsubmit="return confirm('確定要永久刪除【流水號 {{ $item->id }}】');">
                                                    @csrf
                                                    <input name="_method" type="hidden" value="DELETE">
                                                    <button class="btn btn-danger btn-sm my-1">
                                                        <i class="bi bi-trash"></i>刪除
                                                    </button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <div class="alert alert-danger">
                        找不到資料
                    </div>
                @endif
            </div>
        </div>
    </div>
@stop
@section('script')
    <script type="text/javascript"></script>
@stop