routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth', 'badges']], function () {
    //首頁
    Route::get('/', ['as' => 'Home', 'uses' => 'HomeController@index']);
    Route::get('/home', ['as' => 'Home', 'uses' => 'HomeController@index']);
    //主倉儲位
    Route::group(['prefix' => 'stock', 'as' => 'stock.'], function () {
        Route::get('index', ['as' => 'index', 'uses' => 'StockController@index']);
        Route::get('log', ['as' => 'log', 'uses' => 'StockController@log']);
        Route::get('create/{s_id}/{p_id}', ['as' => 'create', 'uses' => 'StockController@create']);
        Route::post('store/{s_id}/{p_id}', ['as' => 'store', 'uses' => 'StockController@store']);
    });
    //優居
    Route::group(['middleware' => ['role:YoHouse']], function () {
        Route::resource('roles', 'RoleController');
        Route::get('users/ajax_detail', ['as' => 'user.ajax_detail', 'uses' => 'UserController@ajax_detail']);
        Route::resource('users', 'UserController');
        Route::resource('sys_config', 'SysConfigController');
        //客製化訂單
        Route::get('order_customized/export/{id}', ['as' => 'order_customized.export', 'uses' => 'OrderCustomizedController@export']);
        Route::get('order_customized/create_by_cc/{id}', ['as' => 'order_customized.create_by_cc', 'uses' => 'OrderCustomizedController@create_by_cc']);
        Route::get('order_customized/create_by_quotation/{id}', ['as' => 'order_customized.create_by_quotation', 'uses' => 'OrderCustomizedController@create_by_quotation']);
        Route::post('order_customized/complete/{id}', ['as' => 'order_customized.complete', 'uses' => 'OrderCustomizedController@complete']);
        Route::resource('order_customized', 'OrderCustomizedController');
        Route::get('PoseinCheckDataLog/{type}', ['as' => 'PoseinCheckDataLog', 'uses' => 'PoseinCheckDataLogController@index']);

        Route::get('check_log_detail/{id}', ['as' => 'check_log_detail', 'uses' => 'PoseinCheckDataLogController@detail']);

        Route::get('order_detail/{id}', ['as' => 'order_detail', 'uses' => 'PoseinCheckDataLogController@order_detail']);

        Route::get('basket_detail', ['as' => 'basket_detail', 'uses' => 'PoseinCheckDataLogController@basket_detail']);

        Route::get('stockAll', ['as' => 'stockAll', 'uses' => 'PoseinCheckDataLogController@stockAll']);

        Route::get('itemp/{stock?}', ['as' => 'itemp', 'uses' => 'PoseinCheckDataLogController@itemp']);

        Route::get('order/{table}', ['as' => 'order', 'uses' => 'PoseinCheckDataLogController@order']);

        Route::get('orderWeight', ['as' => 'orderWeight', 'uses' => 'PoseinCheckDataLogController@orderWeight']);

        Route::get('order_tax_id', ['as' => 'order_tax_id', 'uses' => 'PoseinCheckDataLogController@order_tax_id']);

        Route::get('order_remark', ['as' => 'order_remark', 'uses' => 'PoseinCheckDataLogController@order_remark']);

        Route::get('order_all', ['as' => 'order_all', 'uses' => 'PoseinCheckDataLogController@order_all']);

        Route::get('check_search', ['as' => 'check_search', 'uses' => 'PoseinCheckDataLogController@check_search']);

        Route::get('check_shipment', ['as' => 'check_shipment', 'uses' => 'PoseinCheckDataLogController@check_shipment']);

        Route::get('overweight', ['as' => 'overweight', 'uses' => 'PoseinCheckDataLogController@overweight']);

        Route::get('sales_list', ['as' => 'sales_list', 'uses' => 'PoseinCheckDataLogController@sales_list']);

        Route::get('sales_unchecked', ['as' => 'sales_unchecked', 'uses' => 'PoseinCheckDataLogController@sales_unchecked']);

        Route::get('pre_order', ['as' => 'pre_order', 'uses' => 'PreOrderController@index']);

        //折讓清單
        Route::group(['prefix' => 'credit_note', 'as' => 'credit_note.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'CreditNoteController@index']);
            Route::post('import', ['as' => 'import', 'uses' => 'CreditNoteController@import']);
            Route::post('create_return', ['as' => 'create_return', 'uses' => 'CreditNoteController@create_return']);
            Route::post('confirm', ['as' => 'confirm', 'uses' => 'CreditNoteController@confirm']);
        });

        //未完成訂單總表
        Route::group(['prefix' => 'sales_lost_check', 'as' => 'sales_lost_check.'], function () {
            Route::get('/', ['as' => 'index', 'uses' => 'SalesLostCheckController@index']);
            Route::post('ajax_update', ['as' => 'ajax_update', 'uses' => 'SalesLostCheckController@ajax_update']);
            Route::post('ajax_get_remark', ['as' => 'ajax_get_remark', 'uses' => 'SalesLostCheckController@ajax_get_remark']);
            Route::post('complete', ['as' => 'complete', 'uses' => 'SalesLostCheckController@complete']);
        });

        Route::get('sales_comparison', ['as' => 'sales_comparison', 'uses' => 'PoseinCheckDataLogController@sales_comparison']);

        Route::get('no_print', ['as' => 'no_print', 'uses' => 'PoseinCheckDataLogController@no_print']);

        Route::get('stock_unusual', ['as' => 'stock_unusual', 'uses' => 'PoseinCheckDataLogController@stock_unusual']);

        Route::get('stock_can_sale', ['as' => 'stock_can_sale', 'uses' => 'PoseinCheckDataLogController@stock_can_sale']);

        Route::get('stock_country', ['as' => 'stock_country', 'uses' => 'PoseinCheckDataLogController@stock_country']);

        Route::get('floor_count', ['as' => 'floor_count', 'uses' => 'PoseinCheckDataLogController@floor_count']);

        Route::get('order_plan', ['as' => 'order_plan', 'uses' => 'PoseinCheckDataLogController@order_plan']);

        //排程
        Route::get('schedule_log', ['as' => 'schedule_log', 'uses' => 'ScheduleController@schedule_log']);

        //匯出
        Route::post('export/table', ['as' => 'export_table', 'uses' => 'ExportController@table']);
        //群撿查詢
        Route::get('group_picking', ['as' => 'group_picking', 'uses' => 'PoseinCheckDataLogController@group_picking']);

        //客訴單
        Route::group(['prefix' => 'customer_complaint', 'as' => 'customer_complaint.'], function () {
            Route::get('/', ['as' => 'index', 'uses' => 'CustomerComplaintController@index']);
            Route::post('create', ['as' => 'create', 'uses' => 'CustomerComplaintController@create']);
            Route::post('update', ['as' => 'update', 'uses' => 'CustomerComplaintController@update']);
            Route::post('update_status', ['as' => 'update_status', 'uses' => 'CustomerComplaintController@update_status']);
            Route::get('ajax_get_order', ['as' => 'ajax_get_order', 'uses' => 'CustomerComplaintController@ajax_get_order']);
        });
        //安庫表
        Route::group(['prefix' => 'safety_stock', 'as' => 'safety_stock.'], function () {
            Route::get('/', ['as' => 'index', 'uses' => 'SafetyStockController@index']);
            Route::post('update', ['as' => 'update', 'uses' => 'SafetyStockController@update']);
            Route::post('check', ['as' => 'check', 'uses' => 'SafetyStockController@check']);
        });
        //特殊訂單
        Route::group(['prefix' => 'order_sample', 'as' => 'order_sample.'], function () {
            Route::get('convert', ['as' => 'convert', 'uses' => 'OrderSampleController@convert']);
            Route::get('download_page', ['as' => 'download_page', 'uses' => 'OrderSampleController@download_page']);
            Route::post('confirm', ['as' => 'confirm', 'uses' => 'OrderSampleController@confirm']);
            Route::post('cancel_confirm', ['as' => 'cancel_confirm', 'uses' => 'OrderSampleController@cancel_confirm']);
            Route::post('redo', ['as' => 'redo', 'uses' => 'OrderSampleController@redo']);
            Route::post('update', ['as' => 'update', 'uses' => 'OrderSampleController@update']);
            Route::post('delete', ['as' => 'delete', 'uses' => 'OrderSampleController@delete']);
            Route::post('import', ['as' => 'import', 'uses' => 'OrderSampleController@import']);
            Route::post('order_export', ['as' => 'order_export', 'uses' => 'OrderSampleController@order_export']);
            Route::get('shopee_trans', ['as' => 'shopee_trans', 'uses' => 'OrderSampleController@shopee_trans']);
            Route::post('shopee_trans_convert', ['as' => 'shopee_trans_convert', 'uses' => 'OrderSampleController@shopee_trans_convert']);
            Route::post('shopee_trans_export', ['as' => 'shopee_trans_export', 'uses' => 'OrderSampleController@shopee_trans_export']);
            Route::post('ajax_update_order', ['as' => 'ajax_update_order', 'uses' => 'OrderSampleController@ajax_update_order']);
        });
        //物流
        Route::group(['prefix' => 'transport', 'as' => 'transport.'], function () {
            Route::get('/', ['as' => 'index', 'uses' => 'TransportController@index']);
            Route::get('index_edit', ['as' => 'index_edit', 'uses' => 'TransportController@index_edit']);
            Route::post('index_batch_update', ['as' => 'index_batch_update', 'uses' => 'TransportController@index_batch_update']);
            Route::get('suggest', ['as' => 'suggest', 'uses' => 'TransportController@suggest']);
            Route::post('import_api', ['as' => 'import_api', 'uses' => 'TransportController@import_api']);
            Route::post('ship', ['as' => 'ship', 'uses' => 'TransportController@ship']);
            Route::post('export', ['as' => 'export', 'uses' => 'TransportController@export']);

resources/views/order_customized/index.blade.php
@extends('layouts.base')
@section('title')
    客製化訂單
@stop
@section('css')
    <style type="text/css">
    </style>
@endsection
@section('content')
    <div class="container-fluid">
        <div class="form-row">
            <div class="col"></div>
            <div class="col-auto">
                <a class="btn btn-info" href="{{ route('order_customized.create') }}">
                    <i class="bi bi-plus-lg"></i>新增訂單
                </a>
            </div>
        </div>
        <div class="form-row mt-2">
            <div class="col">
                @if (empty($data) || count($data) == 0)
                    <div class="alert alert-danger">
                        無資料
                    </div>
                @else
                    <div class="FrozenTable" style="font-size:0.8rem; max-height: 87vh;">
                        <table id="table_data" class="table table-bordered table-hover sortable">
                            <thead>
                                <tr>
                                    <th style="width: 4%;">流水號</th>
                                    <th style="width: 7%;">訂單日期</th>
                                    <th style="width: 9%;">客戶</th>
                                    <th style="width: 5%;">銷售員</th>
                                    <th style="width: 11%;">客戶訂單</th>
                                    <th>備註1</th>
                                    <th style="width: 15%;">備註2</th>
                                    <th style="width: 7%;">建立日期</th>
                                    <th style="width: 7%;">操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($data as $item)
                                    <tr>
                                        <td>{{ $item->id }}</td>
                                        <td>{{ $item->order_date }}</td>
                                        <td>{{ $item->customer_text }}</td>
                                        <td>{{ $item->salesman_text }}</td>
                                        <td>{{ $item->order_no }}</td>
                                        <td>{{ $item->remark }}</td>
                                        <td>{{ $item->remark2 }}</td>
                                        <td>{{ $item->created_at }}</td>
                                        <td class="px-0 py-1">
                                            <a class="btn btn-warning btn-sm my-1"
                                                href="{{ route('order_customized.edit', $item->id) }}">
                                                <i class="bi bi-pencil-fill"></i>編輯
                                            </a>
                                            <form method="POST"
                                                action="{{ route('order_customized.destroy', $item->id) }}"
                                                onsubmit="return confirm('確定要刪除該訂單?');">
                                                @csrf
                                                <input name="_method" type="hidden" value="DELETE">
                                                <button class="btn btn-danger btn-sm my-1">
                                                    <i class="bi bi-trash"></i>刪除
                                                </button>
                                            </form>
                                            @if (empty($item->into_erp))
                                                <form action="{{ route('order_customized.complete', $item->id) }}"
                                                    method="POST">
                                                    @csrf
                                                    <button class="btn btn-primary btn-sm my-1">
                                                        <i class="bi bi-check2-square"></i>完成
                                                    </button>
                                                </form>
                                            @else
                                                <form action="{{ route('order_customized.export', $item->id) }}"
                                                    method="get">
                                                    <button class="btn btn-success btn-sm my-1">
                                                        <i class="bi bi-file-earmark-excel"></i>匯出
                                                    </button>
                                                </form>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                @endif
            </div>
        </div>
    </div>
@stop
@section('script')
    <script type="text/javascript"></script>
@stop