routes/web.php
                Route::get('create', ['as' => 'create', 'uses' => 'Product\ProposalController@create']);
                Route::post('store', ['as' => 'store', 'uses' => 'Product\ProposalController@store']);
                Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'Product\ProposalController@edit']);
                Route::patch('update/{id}', ['as' => 'update', 'uses' => 'Product\ProposalController@update']);
                Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'Product\ProposalController@destroy']);
                Route::post('return/{id}', ['as' => 'return', 'uses' => 'Product\ProposalController@return']);
                Route::get('ajax_check_repeat', ['as' => 'ajax_check_repeat', 'uses' => 'Product\ProposalController@ajax_check_repeat']);
            });
        });
        //調轉確認作業
        Route::group(['prefix' => 'order_confirm', 'as' => 'order_confirm.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'OrderConfirmController@index']);
            Route::post('store', ['as' => 'store', 'uses' => 'OrderConfirmController@store']);
        });
        //盤點作業
        Route::group(['prefix' => 'inventory', 'as' => 'inventory.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'InventoryController@index']);
            Route::get('create', ['as' => 'create', 'uses' => 'InventoryController@create']);
            Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'InventoryController@edit']);
            Route::patch('update/{id}', ['as' => 'update', 'uses' => 'InventoryController@update']);
            Route::post('inventory_done/{id}', ['as' => 'inventory_done', 'uses' => 'InventoryController@inventory_done']);
            Route::post('complete/{id}', ['as' => 'complete', 'uses' => 'InventoryController@complete']);
            Route::post('store', ['as' => 'store', 'uses' => 'InventoryController@store']);
            Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'InventoryController@destroy']);
            Route::post('export/{id}', ['as' => 'export', 'uses' => 'InventoryController@export']);
        });
        //收料作業
        Route::group(['prefix' => 'receipt', 'as' => 'receipt.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'ReceiptController@index']);
            Route::post('store', ['as' => 'store', 'uses' => 'ReceiptController@store']);
            Route::get('ajax_get_item', ['as' => 'ajax_get_item', 'uses' => 'ReceiptController@ajax_get_item']);
        });
        //退貨檢驗
        Route::group(['prefix' => 'receipt_return', 'as' => 'receipt_return.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'ReceiptReturnController@index']);
            Route::get('create', ['as' => 'create', 'uses' => 'ReceiptReturnController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'ReceiptReturnController@store']);
            Route::post('update', ['as' => 'update', 'uses' => 'ReceiptReturnController@update']);
            Route::delete('destroy', ['as' => 'destroy', 'uses' => 'ReceiptReturnController@destroy']);
        });
        //外掛倉儲
        Route::group(['prefix' => 'stock', 'as' => 'stock.'], function () {
            Route::get('safety_stock', ['as' => 'safety_stock', 'uses' => 'StockController@safety_stock']);
            Route::get('create_index/{s_id}/{shelf}', ['as' => 'create_index', 'uses' => 'StockController@create_index']);
            Route::get('transfer', ['as' => 'transfer', 'uses' => 'StockController@transfer']);
            Route::post('export/{s_id}', ['as' => 'export', 'uses' => 'StockController@export']);
            Route::post('china_safety_stock_export', ['as' => 'china_safety_stock_export', 'uses' => 'StockController@china_safety_stock_export']);
        });
        //調撥
        Route::group(['prefix' => 'transfer', 'as' => 'transfer.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'TransferController@index']);
            Route::get('check_index', ['as' => 'check_index', 'uses' => 'TransferController@check_index']);
            Route::get('export_index', ['as' => 'export_index', 'uses' => 'TransferController@export_index']);
            Route::post('check', ['as' => 'check', 'uses' => 'TransferController@check']);
            Route::post('export', ['as' => 'export', 'uses' => 'TransferController@export']);
        });
        //蝦皮退貨退款訂單
        Route::group(['prefix' => 'order_return_refund', 'as' => 'order_return_refund.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'OrderReturnRefundController@index']);
            Route::post('import', ['as' => 'import', 'uses' => 'OrderReturnRefundController@import']);
        });
        //報價單
        Route::group(['prefix' => 'quotation', 'as' => 'quotation.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'QuotationController@index']);
            Route::get('create', ['as' => 'create', 'uses' => 'QuotationController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'QuotationController@store']);
            Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'QuotationController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'QuotationController@update']);
            Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'QuotationController@destroy']);
            Route::post('export/{id}', ['as' => 'export', 'uses' => 'QuotationController@export']);
        });
        //蝦皮訂單欄位設定
        Route::group(['prefix' => 'order_columns', 'as' => 'order_columns.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'OrderColumnsController@index']);
            Route::post('update', ['as' => 'update', 'uses' => 'OrderColumnsController@update']);
            Route::post('update_idx', ['as' => 'update_idx', 'uses' => 'OrderColumnsController@update_idx']);
        });
        //國定假日設定
        Route::group(['prefix' => 'holiday', 'as' => 'holiday.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'HolidayController@index']);
            Route::get('update', ['as' => 'update', 'uses' => 'HolidayController@update']);
        });
        //貨櫃進口
        Route::group(['prefix' => 'container_import', 'as' => 'container_import.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'ContainerImportController@index']);
            Route::get('create', ['as' => 'create', 'uses' => 'ContainerImportController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'ContainerImportController@store']);
            Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'ContainerImportController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'ContainerImportController@update']);
            Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'ContainerImportController@destroy']);
            Route::post('finish/{id}', ['as' => 'finish', 'uses' => 'ContainerImportController@finish']);
        });
        //帳號管理
        Route::group(['prefix' => 'account', 'as' => 'account.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'AccountController@index']);
            Route::get('create', ['as' => 'create', 'uses' => 'AccountController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'AccountController@store']);
            Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'AccountController@destroy']);
            Route::post('import', ['as' => 'import', 'uses' => 'AccountController@import']);
        });
        //內部採購
        Route::group(['prefix' => 'purchase', 'as' => 'purchase.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'PurchaseController@index']);
        });
        //出勤
        Route::group(['prefix' => 'attendance', 'as' => 'attendance.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'AttendanceController@index']);
            Route::post('ajax_check_in', ['as' => 'ajax_check_in', 'uses' => 'AttendanceController@ajax_check_in']);
        });
        //行事曆
        Route::group(['prefix' => 'calendar', 'as' => 'calendar.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'CalendarController@index']);
            Route::get('create', ['as' => 'create', 'uses' => 'CalendarController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'CalendarController@store']);
            Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'CalendarController@edit']);
            Route::patch('update/{id}', ['as' => 'update', 'uses' => 'CalendarController@update']);
            Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'CalendarController@destroy']);
        });
    });
    //其他公司
    Route::group(['middleware' => ['role:YoHouse2']], function () {
        Route::group(['prefix' => 'erp', 'as' => 'erp.'], function () {
            //銷貨作業
            Route::group(['prefix' => 'sales', 'as' => 'sales.'], function () {
                Route::get('index', ['as' => 'index', 'uses' => 'Erp\SalesController@index']);
                Route::get('create', ['as' => 'create', 'uses' => 'Erp\SalesController@create']);
                Route::post('store', ['as' => 'store', 'uses' => 'Erp\SalesController@store']);
                Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'Erp\SalesController@edit']);
                Route::patch('update/{id}', ['as' => 'update', 'uses' => 'Erp\SalesController@update']);
                Route::delete('destroy/{id}', ['as' => 'destroy', 'uses' => 'Erp\SalesController@destroy']);
            });
        });
    });
});
//真桂森林
Route::group(['prefix' => 'cinforest', 'as' => 'cinforest.'], function () {
    Route::get('index', ['as' => 'index', 'uses' => 'CinForestController@index']);

app/Models/yherp/CinForest.php
<?php

namespace App\Models\yherp;

use Illuminate\Database\Eloquent\Model;

class CinForest extends Model
{
    protected $connection = 'mysql';
    protected $table = 'cinforest';

    protected $primaryKey = 'PCOD1';
    protected $keyType = 'string';
    public $incrementing = false;

    protected $fillable = [
        'PCOD1',
        'ConsignTran'
    ];
}

app/Http/Controllers/CinForestController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\yherp\CinForest;
use App\Services\CinForestService;

class CinForestController extends Controller
{
    private $cinforestService = null;

    function __construct(CinForestService $cinforestService)
    {
        $this->cinforestService = $cinforestService;
    }

    public function index()
    {
        $data = $this->cinforestService->GetOrder();
        return view('cinforest.index', $data);
    }

    public function update(Request $request)
    {
        CinForest::updateOrCreate(
            ['PCOD1' => $request->get('sale_no')],
            ['ConsignTran' => $request->get('tran_no')]
        );
        return redirect()->route('cinforest.index')->with('status', '更新成功');
    }
}

resources/views/cinforest/index.blade.php
@extends('layouts.master')
@section('master_title')
    真桂森林-訂單
@stop
@section('master_css')
    <style type="text/css">
        .status_1 {
            background-color: #ffeeba;
        }

        .status_2 {
            background-color: #8fd19e;
        }
    </style>
@endsection
@section('master_body')
    {{-- Modal 填寫物流單號 --}}
    <div id="modal_tran_no" class="modal">
        <div class="modal-dialog modal-dialog-centered modal-xl">
            <div class="modal-content">
                <form method="POST" action="{{ route('cinforest.update') }}">
                    @method('PATCH')
                    @csrf
                    <div class="modal-header">
                        <h1 class="modal-title">填寫物流單號</h1>
                        <button type="button" class="close" data-dismiss="modal">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="FrozenTable">
                            <table class="table table-bordered sortable">
                                <tbody>
                                    <tr>
                                        <th style="width: 15%;">銷貨備註3</th>
                                        <td id="td_pbak3"></td>
                                    </tr>
                                    <tr>
                                        <th>內部備註</th>
                                        <td id="td_insidenote"></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <hr>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">新竹物流單號(10碼)</span>
                            </div>
                            <input class="form-control" id="input_tran_no" name="tran_no" type="text"
                                placeholder="請在此輸入新竹物流單號" maxlength="10">
                            <input id="input_sale_no" name="sale_no" type="hidden" value="">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success">確定</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="form-row mt-2">
            <div class="col">
                <div class="FrozenTable" style="max-height: 98vh;">
                    <table class="table table-bordered sortable">
                        <thead>
                            <tr>
                                <th>狀態</th>
                                <th style="width: 14%;">原始訂單編號</th>
                                <th style="width: 8%;">銷貨日期</th>
                                <th>銷貨備註3</th>
                                <th>內部備註</th>
                                <th style="width: 18%;">銷貨內容</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $o)
                                @if (!$editable)
                                    @continue
                                @endif
                                <tr class="status_{{ $o->status }}">
                                    <td>
                                        @switch($o->status)
                                            @case(1)
                                                <button class="btn btn-info btn-sm" type="button" data-toggle="modal"
                                                    data-PCOD1="{{ $o->PCOD1 }}" data-PBAK3="{{ $o->PBAK3 }}"
                                                    data-insidenote="{{ $o->InsideNote }}"
                                                    data-target="#modal_tran_no">填寫物流單號</button>
                                            @break

                                            @case(2)
                                                回填TMS<br>
                                                {{ $o->cinforest->ConsignTran }}
                                            @break
                                        @endswitch
                                    </td>
                                    <td>{{ $o->PJONO }}</td>
                                    <td>{{ $o->PDAT1 }}</td>
                                    <td>{{ $o->PBAK3 }}</td>
                                    <td>{{ $o->InsideNote }}</td>
                                    <td>
                                        <div class="FrozenTable" style="max-height: 98vh;">
                                            <table class="table table-bordered table-hover sortable bg-white">
                                                <tbody>
                                                    @foreach ($o->Histin as $d)
                                                        <tr>
                                                            <td>{{ $d->HINAM }}</td>
                                                            <td style="width: 20%">{{ number_format($d->HINUM) }}</td>
                                                        </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop
@section('master_js')
    <script type="text/javascript">
        $('#modal_tran_no').on('shown.bs.modal', function() {
            $('#input_tran_no').trigger('focus')
        })
        $('button[data-target="#modal_tran_no"]').click(function() {
            var data = $(this).data();
            $('#input_sale_no').val(data.pcod1);
            $('#td_pbak3').text(data.pbak3);
            $('#td_insidenote').text(data.insidenote);
        });
    </script>
@stop